default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"

test:
  <<: *default
  database: instagram_test

production:
  <<: *default
  database: instagram_production

development:
  <<: *default
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"


development:
  <<: *default
  database: instagram_development

test:
  <<: *default
  database: instagram_test


production:
  <<: *default
  database: instagram_production
  username: instagram
  password: <%= ENV["INSTAGRAM_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
